# Generated by Django 4.2.9 on 2026-04-28 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payout', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledgerentry',
            options={},
        ),
        migrations.RenameIndex(
            model_name='idempotencykey',
            new_name='payout_idem_merchan_e9384c_idx',
            old_name='payout_idem_merchan_key_idx',
        ),
        migrations.RenameIndex(
            model_name='idempotencykey',
            new_name='payout_idem_expires_676b88_idx',
            old_name='payout_idem_expires_idx',
        ),
        migrations.RemoveField(
            model_name='ledgerentry',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ledgerentry',
            name='payout',
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('hold', 'Hold'), ('release', 'Release')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payout.merchant'),
        ),
    ]
